site_name: Randev user guide
site_url: https://help.randev.io/
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Store owner guide: store-owner-guide/index.md
  - Staff guide: staff-guide/index.md
  - User guide: user-guide/index.md
  - About:
      - Getting in touch: about/contact.md
      - Release Notes: about/release-notes.md
      - Contributing: about/contributing.md
theme:
  name: material
  favicon: img/logo.ico
  logo: img/logo-white.png
  custom_dir: overrides
  icon:
    alternate: fontawesome/globe-europe-solid
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
#    - name: English
#      link: ./en/
#      lang: en
    - name: Français
      link: ./fr/
      lang: fr
#    - name: العربيّة
#      link: ./ar/
#      lang: ar
plugins:
  - glightbox
  - mkdocs-video
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang:
#        - en
        - fr
#        - ar
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
#          default: true
          locale: en
          name: English
          site_name: Randev documentation
        - build: true
          default: true
          locale: fr
          name: Français
          nav_translations:
            About: A propos
            Contributing: Contributions
            Getting in touch: Prise de contact
            Getting started: Démarrage rapide
            Home: Accueil
            Release Notes: Notes de la release
            Staff guide: Guide employé
            Store owner guide: Guide patron
            User guide: Guide utilisateur
          site_name: Documentation Randev
        - build: true
          default: false
          locale: ar
          name: العربيّة
          nav_translations:
            About: حول البرنامج
            Contributing: المساهمة
            Getting in touch: الاتصال بنا
            Getting started: بداية سريعة
            Home: البداية
            Release Notes: ملاحظات الاصدار
            Staff guide: دليل العملة والموضفين
            Store owner guide: دليل صاحب المحل
            User guide: دليل المستخدم
          site_name: رندف - دليل المستخدم
      reconfigure_material: true
      reconfigure_search: true
